### ISSUE TITLE
org.junit and org.hamcrest do not exist

### ISSUE THREAD

**Issue by mj010273** [IanDarwin/javasrc#1]
New to maven and git so hope this is correct way to notify you?

Running Maven on the command line (Maven binares for Windows in a Cygwin terminal); fails with the following errors (root of path cut to save space):

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project javasrc: Compilation failure: Compilation failure:
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[3,17] package org.junit does not exist
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[4,24] package org.junit does not exist
[ERROR] <CUT>/src/main/java/testing/PersonTest.java:[3,1] package org.junit does not exist
[ERROR] <CUT>/src/main/java/testing/PersonTest.java:[4,24] package org.junit does not exist
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[3,27] package org.hamcrest does not exist
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[3,1] static import only from classes and interfaces
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[4,27] package org.hamcrest does not exist
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[4,1] static import only from classes and interfaces
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[5,27] package org.hamcrest does not exist
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[5,1] static import only from classes and interfaces
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[6,24] package org.junit does not exist
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[6,1] static import only from classes and interfaces
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[8,17] package org.junit does not exist
[ERROR] <CUT>/src/main/java/testing/IntegerTest.java:[3,23] package junit.framework does not exist
[ERROR] <CUT>/src/main/java/testing/IntegerTest.java:[9,34] cannot find symbol
[ERROR] symbol: class TestCase
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[10,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[18,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[25,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[32,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/testing/PersonTest.java:[10,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class testing.PersonTest
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[13,10] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class testing.HamcrestDemo
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[15,17] cannot find symbol
[ERROR] symbol:   method assertFalse(java.lang.String,boolean)
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[22,17] cannot find symbol
[ERROR] symbol:   method assertFalse(java.lang.String,boolean)
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[29,17] cannot find symbol
[ERROR] symbol:   method assertFalse(java.lang.String,boolean)
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/lang/ArrayEqualsWorks.java:[36,17] cannot find symbol
[ERROR] symbol:   method assertFalse(java.lang.String,boolean)
[ERROR] location: class lang.ArrayEqualsWorks
[ERROR] <CUT>/src/main/java/testing/PersonTest.java:[14,17] cannot find symbol
[ERROR] symbol:   method assertEquals(java.lang.String,java.lang.String,java.lang.String)
[ERROR] location: class testing.PersonTest
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[17,31] cannot find symbol
[ERROR] symbol:   method containsString(java.lang.String)
[ERROR] location: class testing.HamcrestDemo
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[18,31] cannot find symbol
[ERROR] symbol:   method equalTo(java.lang.String)
[ERROR] location: class testing.HamcrestDemo
[ERROR] <CUT>/src/main/java/testing/HamcrestDemo.java:[19,35] cannot find symbol
[ERROR] symbol:   method containsString(java.lang.String)
[ERROR] location: class testing.HamcrestDemo
[ERROR] <CUT>/src/main/java/testing/IntegerTest.java:[13,17] cannot find symbol
[ERROR] symbol:   method assertEquals(int,int)
[ERROR] location: class testing.IntegerTest
[ERROR] <CUT>/src/main/java/testing/IntegerTest.java:[15,17] cannot find symbol
[ERROR] symbol:   method assertEquals(int,int)
[ERROR] location: class testing.IntegerTest
[ERROR] <CUT>/src/main/java/testing/IntegerTest.java:[18,25] cannot find symbol
[ERROR] symbol:   method fail(java.lang.String)
[ERROR] location: class testing.IntegerTest

**Comment by IanDarwin** [comment]
This has been solved for some time, closing this.
