### ISSUE TITLE
call to undefined method in EnumDemo.java

### ISSUE THREAD

**Issue by giatorta** [IanDarwin/javasrc#14]
in [EnumDemo.java](https://github.com/IanDarwin/javasrc/blob/0b1c3af22779581fa90606e819b0273510c797a9/main/src/main/java/structure/EnumDemo.java), method `driverIsAggressive()` is called at line 25, but such method does not exist

**Comment by IanDarwin** [comment]
Corrected in 332fb553: method was present but misnamed. Thanks for reporting.
